name: TaskTracker Build and Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [develop]
env:
  DOTNET_VERSION: '8.0.x'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: List solution files
        run: find . -name "*.sln" -type f
      - name: Install dependencies
        run: dotnet restore TaskTracker/TaskTracker.sln
      - name: Run build
        run: dotnet build TaskTracker/TaskTracker.sln --configuration Release --no-restore
  test:
    name: Test
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install Dependencies
        run: dotnet restore TaskTracker/TaskTracker.sln
      - name: Run Build
        run: dotnet build TaskTracker/TaskTracker.sln --configuration Release --no-restore
      - name: Generate Test Results
        run: dotnet test TaskTracker/TaskTracker.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFilePrefix=test-results" --results-directory ./coverage
      - name: Upload Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: coverage/test-results*.trx
          reporter: dotnet-trx
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
      - name: Generate Test Coverage
        run: dotnet test TaskTracker/TaskTracker.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Join Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
        with:
          reports: coverage/**/coverage.cobertura.xml
          targetdir: coverage
          reporttypes: 'Cobertura'
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/*.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '85 90'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && always() && hashFiles('code-coverage-results.md') != ''
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Write to Job Summary
        if: always()
        run: |
          if [ -f code-coverage-results.md ]; then
            cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No coverage results found" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Build Tag
        if: github.event_name == 'push'
        run: |
          git fetch --tags origin
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          GIT_TAGS=$(git tag | grep -E '^TaskTracker-[0-9]+\.[0-9]+(\.[0-9]+)?$' || true)
          if [ -z "$GIT_TAGS" ]; then
            LATEST="0.0.0"
          else
            LATEST=$(
              git tag --list |
              grep -E '^TaskTracker-[0-9]+\.[0-9]+(\.[0-9]+)?$' |
              sort -V |
              tail -n 1 |
              sed 's/^TaskTracker-//'
            )
          fi
          if echo $LATEST | grep -E '^[0-9]+\.[0-9]+$'; then
            BUMPED="${LATEST}.0"
          else
            BUMPED=$(echo $LATEST | awk -F. '{ print $1 "." $2 "." ($3 + 1) }')
          fi
          echo "bumping ${LATEST} to ${BUMPED}"
          git tag --annotate "TaskTracker-${BUMPED}" --message "TaskTracker via GitHub Actions"
          git push origin "TaskTracker-${BUMPED}"